# 나이브 베이즈

In [1]:
import pandas as pd
import re

df = pd.read_csv('sms_spam.csv', encoding='ISO-8859-1' )

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5559 entries, 0 to 5558
Data columns (total 2 columns):
type    5559 non-null object
text    5559 non-null object
dtypes: object(2)
memory usage: 86.9+ KB


In [3]:
df.head()

type                                               text
0   ham  Hope you are having a good week. Just checking in
1   ham                            K..give back my thanks.
2   ham        Am also doing in cbe only. But have to pay.
3  spam  complimentary 4 STAR Ibiza Holiday or £10,000...
4  spam  okmail: Dear Dave this is your final notice to...

In [4]:
df['text'][3]

'complimentary 4 STAR Ibiza Holiday or £10,000 cash needs your URGENT collection. 09066364349 NOW from Landline not to lose out! Box434SK38WP150PPM18+'

In [5]:
text = df['text'][3]
text = re.sub('\W', ' ', text)
#  \W 문자+숫자(alphanumeric)가 아닌 문자와 매치, [^a-zA-Z0-9]와 동일한 표현식 = 즉, 특수문자
text

'complimentary 4 STAR Ibiza Holiday or  10 000 cash needs your URGENT collection  09066364349 NOW from Landline not to lose out  Box434SK38WP150PPM18 '

In [6]:
text = re.sub('\d', '', text)
# \d 숫자와 매치, [0-9]와 동일한 표현식
# c.f) 대문자와 소문자에 따라 정반대의 결과. 예) \D 숫자가 아닌 것과 매치, [^0-9]와 동일한 표현
text

'complimentary  STAR Ibiza Holiday or    cash needs your URGENT collection   NOW from Landline not to lose out  BoxSKWPPPM '

In [7]:
text = re.sub('[ \t]+' , ' ', text)
# [ \t]+ 줄 끝이나 줄 맨앞에 여분의 공백을 일치시킨다.
text

'complimentary STAR Ibiza Holiday or  cash needs your URGENT collection NOW from Landline not to lose out BoxSKWPPPM '

In [8]:
text = None
text

In [9]:
df.head()

type                                               text
0   ham  Hope you are having a good week. Just checking in
1   ham                            K..give back my thanks.
2   ham        Am also doing in cbe only. But have to pay.
3  spam  complimentary 4 STAR Ibiza Holiday or £10,000...
4  spam  okmail: Dear Dave this is your final notice to...

In [10]:
df['text'][1]

'K..give back my thanks.'

In [11]:
text_list = []
for i in range(len(df)):
    text = df['text'][i]
    text = re.sub('[^\w\s]', '', text)
    text = re.sub('\d', '', text)
    text = re.sub('[ \t]+' , ' ', text)
    text_list.append(text)
#     text_list.append(re.split(' ', text))

In [12]:
text_list[0]

'Hope you are having a good week Just checking in'

In [13]:
print(text_list[:5])

['Hope you are having a good week Just checking in', 'Kgive back my thanks', 'Am also doing in cbe only But have to pay', 'complimentary STAR Ibiza Holiday or  cash needs your URGENT collection NOW from Landline not to lose out BoxSKWPPPM', 'okmail Dear Dave this is your final notice to collect your Tenerife Holiday or CASH award Call from landline TCs SAE Box CWWX ppm']


In [14]:
text_list

['Hope you are having a good week Just checking in',
 'Kgive back my thanks',
 'Am also doing in cbe only But have to pay',
 'complimentary STAR Ibiza Holiday or  cash needs your URGENT collection NOW from Landline not to lose out BoxSKWPPPM',
 'okmail Dear Dave this is your final notice to collect your Tenerife Holiday or CASH award Call from landline TCs SAE Box CWWX ppm',
 'Aiya we discuss later lar Pick u up at is it',
 'Are you this much buzy',
 'Please ask mummy to call father',
 'Marvel Mobile Play the official Ultimate Spiderman game  on ur mobile right now Text SPIDER to for the game we ll send u a FREE Ball wallpaper',
 'fyi Im at usf now swing by the room whenever',
 'Sure thing big man i have hockey elections at shouldnt go on longer than an hour though',
 'I anything lor',
 'By march ending i should be ready But will call you for sure The problem is that my capital never complete How far with you Hows work and the ladies',
 'Hmm well night night ',
 'K Ill be sure to get

In [15]:
from sklearn.feature_extraction.text import CountVectorizer
# scikit-learn 문서 전처리 기능
# CounterVectorizer : 문서 집합에서 단어 토큰을 생성하고 각 단어의 수를 세어 BOW(Bag of words) 인코딩한 벡터를 만든다.

In [16]:
vect = CountVectorizer(min_df=0., max_df=1.0)
vect

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=0.0,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [17]:
X = vect.fit_transform(text_list) 
#Learn the vocabulary dictionary and return term-document matrix.

In [18]:
type(X) # sparse matrix

scipy.sparse.csr.csr_matrix

In [19]:
print(X)

  (0, 3471)	1
  (0, 1198)	1
  (0, 3762)	1
  (0, 8103)	1
  (0, 2885)	1
  (0, 3106)	1
  (0, 367)	1
  (0, 8500)	1
  (0, 3281)	1
  (1, 7326)	1
  (1, 4743)	1
  (1, 534)	1
  (1, 3825)	1
  (2, 5319)	1
  (2, 7493)	1
  (2, 3099)	1
  (2, 975)	1
  (2, 5105)	1
  (2, 1126)	1
  (2, 1964)	1
  (2, 227)	1
  (2, 235)	1
  (2, 3471)	1
  (3, 848)	1
  (3, 5181)	1
  :	:
  (5557, 3744)	2
  (5557, 1165)	1
  (5557, 7000)	1
  (5557, 31)	1
  (5557, 289)	1
  (5557, 3197)	1
  (5557, 2189)	2
  (5557, 2198)	1
  (5557, 6029)	2
  (5557, 4395)	1
  (5557, 6670)	1
  (5557, 1701)	1
  (5557, 8164)	1
  (5557, 3883)	1
  (5557, 7825)	1
  (5557, 3610)	1
  (5557, 3596)	1
  (5557, 4939)	1
  (5557, 975)	1
  (5558, 6439)	1
  (5558, 2581)	1
  (5558, 1008)	1
  (5558, 1726)	1
  (5558, 4956)	1
  (5558, 3106)	1


In [20]:
X.todense()
#Return a dense matrix representation of this matrix.

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [21]:
#매트릭스의 종류는 2가지
# 1. dens matrix : 모든 정보를 다 가지고 있음
# 2. sparse matrix : 예를 들어, 'Kgive back my thanks' kigve/ back/ my / thanks 
# 2. (0, 3471) 1 : 0번째 로우('Kgive back my thanks' ), 3471(kgive 컬럼이 3471번째에 있다. 순서대로 컬럼이 지정되지 않는군!)
# 2. 1의 의미 : 0번째 로우에 3471 컬럼에 해당하는 kgive 단어가 1개 있다!  // 2는 단어가 2개 있다는 뜻
# 2. 0은 없는 이유 : 있는 단어만 좌표를 찍어 나타내줌. c.f) dense는 모든 정보를 표현함(비경제적)

In [22]:
#로우는 문장갯수, 컬럼은 단어단위로 분할

In [23]:
X.todense()
#Return a dense matrix representation of this matrix.

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [24]:
X.shape

(5559, 8589)

In [25]:
df.shape

(5559, 2)

In [26]:
df.type.head()
# 데이터프레임의 컬럼을 지정
# df['type'] == df.type

0     ham
1     ham
2     ham
3    spam
4    spam
Name: type, dtype: object

In [27]:
df['type'].head() # df.type.head()

0     ham
1     ham
2     ham
3    spam
4    spam
Name: type, dtype: object

In [28]:
df.type.map({'ham' : 0, 'spam' : 1}).head()
# df['type'].map({'ham' : 0, 'spam' : 1}).head()

0    0
1    0
2    0
3    1
4    1
Name: type, dtype: int64

In [29]:
#데이터 프레임 자료를 array 형태로 변형 
import numpy as np
y = np.array(df.type.map({'ham' : 0, 'spam' : 1}))
# y=np.array(df['type'].map({'ham' : 0, 'spam' : 1}))

In [30]:
y

array([0, 0, 0, ..., 1, 1, 0], dtype=int64)

In [31]:
y.shape

(5559,)

# Train, Test set 나누기

In [32]:
X.shape[0]*0.8

4447.2

In [33]:
X

<5559x8589 sparse matrix of type '<class 'numpy.int64'>'
	with 70442 stored elements in Compressed Sparse Row format>

In [34]:
y

array([0, 0, 0, ..., 1, 1, 0], dtype=int64)

In [35]:
from sklearn.model_selection import train_test_split

x_train, x_test = train_test_split(X, test_size=0.3, random_state=42)
x_train.shape, x_test.shape

((3891, 8589), (1668, 8589))

## y(레이블) : (x, ) 형태
* y=np.array(df['type'].map({'ham' : 0, 'spam' : 1}))
* mapping 함수(map) : 범주형 - 연속형 변수 변환
* df['Gender']=df['Gender'].replace('Male',0) 처럼 replace 한 후에 array로 변환해도 될 듯!

In [36]:
y_train, y_test = train_test_split(y, test_size=0.3, random_state=42)
y_train = np.array(y_train)
y_test = np.array(y_test)
y_train.shape, y_test.shape

((3891,), (1668,))

# 1. 베르누이 분포 나이브 베이즈

In [37]:
from sklearn.naive_bayes import BernoulliNB
model_bern = BernoulliNB()

In [38]:
model_bern.fit(x_train, y_train)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [39]:
pre = model_bern.predict(x_test)
pre

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [40]:
y_test

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [41]:
print((pre==y_test).mean())

0.9664268585131894


# scikit-learn의 교차검증 기능

* https://datascienceschool.net/view-notebook/266d699d748847b3a3aa7b9805b846ae/

### 단순 데이터 분리¶
- 단순 데이터를 나누는 것과 교차검증의 차이 확인.

In [42]:
dfX_train, dfX_test, dfy_train, dfy_test = train_test_split(X, y, test_size=0.3, random_state=42)
dfX_train.shape, dfy_train.shape, dfX_test.shape, dfy_test.shape

((3891, 8589), (3891,), (1668, 8589), (1668,))

- 교차 검증의 장점은 train_test_split와 비교해보면 train_test_split는 데이터를 무작위로 나눔. 데이터를 무작위로 나눌 때 
- 훈련 세트 ==>  분류하기 어려운 샘플
- 테스트세트 ==> 분류하기 쉬운 샘플
- 테스트 세트의 정확도는 비현실적으로 높게 나올 것입니다. 반대의 경우라면 테스트 세트의 정확도는 비현실적으로 낮게 나옴

- 그러나 교차 검증을 사용하면 테스트 세트에 각 샘플이 정확하게 한번씩 들어가고 각 샘플은 폴드 중 하나에 속하며 각 폴드는 한번씩 테스트 세트가 됨 그렇기 때문에 교차 검증의 점수를 높이기 위해서는 데이터 셋에 있는 모든 샘플에 대해 모델이 잘 일반화 되어야 함

- 데이터를 여러개로 나누면 모델이 훈련 데이터에 얼마나 민감한지 알 수가 있음 
- 교차 검증의 주요 단점은 연산 비용이 늘어남 모델을 k개 만들어야 하므로 데이터를 한 번 나눴을때보다 대략 k배 더 느림

# K-fold 교차검증

- scikit-learn 패키지의 model_selection 서브 패키지는 KFold 클래스를 비롯한 다양한 교차검증 생성기를 제공한다. 이 생성기의 split 메서드는 학습용과 검증용의 데이터 인덱스를 출력하는 파이썬 반복자(iterator)를 반환한다.

In [43]:
from sklearn.naive_bayes import BernoulliNB
model_BNB = BernoulliNB()

* KFold : scikit-learn 패키지의 model_selection 서브 패키지는 KFold 클래스를 비롯한 다양한 교차검증 생성기를 제공

In [44]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

* KFold 함수를 사용하려면 아래와 같이 코드가 길어진다


In [45]:
# scores = np.zeros(5)
# cv = KFold(5, shuffle=False, random_state=0)
# for i, (idx_train, idx_test) in enumerate(cv.split(df)):
#     df_train = df.iloc[idx_train]
#     df_test = df.iloc[idx_test]
    
#     model = sm.OLS.from_formula("MEDV ~ " + "+".join(boston.feature_names), data=df_train)
#     result = model.fit()
    
#     pred = result.predict(df_test)
#     rss = ((df_test.MEDV - pred) ** 2).sum()
#     tss = ((df_test.MEDV - df_test.MEDV.mean())** 2).sum()
#     rsquared = 1 - rss / tss
    
#     scores[i] = rsquared
#     print("학습 R2 = {:.8f}, 검증 R2 = {:.8f}".format(result.rsquared, rsquared))

* cross_val_score : 교차검증을 반복하는 코드를 더 간단하게 만들어주는 함수 

In [46]:
cross_val_score(model_BNB, X, y, scoring="accuracy") ##분류이므로 scoring = accuracy, 회기는 r2

array([0.9735564 , 0.97409606, 0.96438208])

In [47]:
cross_val_score(model_BNB, X, y, scoring="accuracy", cv=5) #교차검증에서 데이터 전체를 넣어야 됨.
# cross_val_score(model, X, y, scoring=None, cv=None)
# model : 회귀 분석 모형
# scoring : 성능 검증에 사용할 함수 이름
# cv : 교차검증 생성기 객체 또는 숫자. None이면 KFold(3), 숫자 k이면 KFold(k)

array([0.98203055, 0.96945193, 0.9729973 , 0.9729973 , 0.96579658])

* 모델을 다시 튜닝한다기 보다는, 이미 만들어져 있는 모델로 교차검증을 해서 더 정확하게 분류한다는 의미같음.

In [48]:
print('교차검증 :', cross_val_score(model_BNB, X, y, scoring="accuracy", cv=5).mean()), print('교차검증 X : ', (pre==y_test).mean())

교차검증 : 0.9726547317804558
교차검증 X :  0.9664268585131894


(None, None)

In [49]:
# cross_val_score(model_BNB, X, y, scoring="accuracy", cv=5).mean(), cross_val_score(model_BNB, X, y, scoring="accuracy", cv=cv).mean()

# 가우시안 정규 분포 나이브 베이즈